#ifndef __RENALIBS_RENARICH_ERRCODES_H__
#define __RENALIBS_RENARICH_ERRCODES_H__

#define RENA_ERR_ILLEGAL_COLOR_CODE             0x000001
#define RENA_ERR_ILLEGAL_STYLE                  0x000002
#define RENA_ERR_INDEX_OUT_OF_RANGE             0x000003

#define RENA_ERR_ICU_REGEX_COMPILE_FAILED       0x010000
#define RENA_ERR_ICU_REGEX_MATCH_FAILED         0x010001
#define RENA_ERR_ICU_REGEX_MATCH_REPLACE_FAILED 0x010002

#define RENA_ERR_UNEXPECTED                     0xFFFFFF

#endif // __RENALIBS_RENARICH_ERRCODES_H__
