/**
 * This file is auto-generated by `src/tools/update_box_chars.py`
 * 
 * DO NOT EDIT!!!
 * 
 * If something is wrong, please fix it in `src/tools/templates/update_box_chars/box_chars.h.in` first
 */

#ifndef __RENARICH_BUILTIN_BOX_CHARS_H__
#define __RENARICH_BUILTIN_BOX_CHARS_H__

#include<string>

namespace rena::builtin {

    extern const std::string bc_sll_h;
    extern const std::wstring bc_sll_h_w;
    extern const std::string bc_sll_v;
    extern const std::wstring bc_sll_v_w;
    extern const std::string bc_sll_dr;
    extern const std::wstring bc_sll_dr_w;
    extern const std::string bc_sll_dl;
    extern const std::wstring bc_sll_dl_w;
    extern const std::string bc_sll_ur;
    extern const std::wstring bc_sll_ur_w;
    extern const std::string bc_sll_ul;
    extern const std::wstring bc_sll_ul_w;
    extern const std::string bc_sll_vr;
    extern const std::wstring bc_sll_vr_w;
    extern const std::string bc_sll_vl;
    extern const std::wstring bc_sll_vl_w;
    extern const std::string bc_sll_dh;
    extern const std::wstring bc_sll_dh_w;
    extern const std::string bc_sll_uh;
    extern const std::wstring bc_sll_uh_w;
    extern const std::string bc_sll_vh;
    extern const std::wstring bc_sll_vh_w;
    extern const std::string bc_slh_h;
    extern const std::wstring bc_slh_h_w;
    extern const std::string bc_slh_v;
    extern const std::wstring bc_slh_v_w;
    extern const std::string bc_slh_dr;
    extern const std::wstring bc_slh_dr_w;
    extern const std::string bc_slh_dl;
    extern const std::wstring bc_slh_dl_w;
    extern const std::string bc_slh_ur;
    extern const std::wstring bc_slh_ur_w;
    extern const std::string bc_slh_ul;
    extern const std::wstring bc_slh_ul_w;
    extern const std::string bc_slh_vr;
    extern const std::wstring bc_slh_vr_w;
    extern const std::string bc_slh_vl;
    extern const std::wstring bc_slh_vl_w;
    extern const std::string bc_slh_dh;
    extern const std::wstring bc_slh_dh_w;
    extern const std::string bc_slh_uh;
    extern const std::wstring bc_slh_uh_w;
    extern const std::string bc_slh_vh;
    extern const std::wstring bc_slh_vh_w;
    extern const std::string bc_dll_h;
    extern const std::wstring bc_dll_h_w;
    extern const std::string bc_dll_v;
    extern const std::wstring bc_dll_v_w;
    extern const std::string bc_dll_dr;
    extern const std::wstring bc_dll_dr_w;
    extern const std::string bc_dll_dl;
    extern const std::wstring bc_dll_dl_w;
    extern const std::string bc_dll_ur;
    extern const std::wstring bc_dll_ur_w;
    extern const std::string bc_dll_ul;
    extern const std::wstring bc_dll_ul_w;
    extern const std::string bc_dll_vr;
    extern const std::wstring bc_dll_vr_w;
    extern const std::string bc_dll_vl;
    extern const std::wstring bc_dll_vl_w;
    extern const std::string bc_dll_dh;
    extern const std::wstring bc_dll_dh_w;
    extern const std::string bc_dll_uh;
    extern const std::wstring bc_dll_uh_w;
    extern const std::string bc_dll_vh;
    extern const std::wstring bc_dll_vh_w;
    extern const std::string bc_rll_h;
    extern const std::wstring bc_rll_h_w;
    extern const std::string bc_rll_v;
    extern const std::wstring bc_rll_v_w;
    extern const std::string bc_rll_dr;
    extern const std::wstring bc_rll_dr_w;
    extern const std::string bc_rll_dl;
    extern const std::wstring bc_rll_dl_w;
    extern const std::string bc_rll_ur;
    extern const std::wstring bc_rll_ur_w;
    extern const std::string bc_rll_ul;
    extern const std::wstring bc_rll_ul_w;
    extern const std::string bc_rll_vr;
    extern const std::wstring bc_rll_vr_w;
    extern const std::string bc_rll_vl;
    extern const std::wstring bc_rll_vl_w;
    extern const std::string bc_rll_dh;
    extern const std::wstring bc_rll_dh_w;
    extern const std::string bc_rll_uh;
    extern const std::wstring bc_rll_uh_w;
    extern const std::string bc_rll_vh;
    extern const std::wstring bc_rll_vh_w;

} // namespace rena::builtin

#endif // __RENARICH_BUILTIN_BOX_CHARS_H__
