/**
 * This file is auto-generated by `src/tools/update_box_chars.py`
 * 
 * DO NOT EDIT!!!
 * 
 * If something is wrong, please fix it in `src/tools/templates/update_box_chars/box_chars.cpp.in` first
 */

#include"box_chars.h"

const std::string rena::builtin::bc_table[4][11] = {
    { "─" , "│" , "┌" , "┐" , "└" , "┘" , "├" , "┤" , "┬" , "┴" , "┼"  } ,
    { "━" , "┃" , "┏" , "┓" , "┗" , "┛" , "┣" , "┫" , "┳" , "┻" , "╋"  } ,
    { "═" , "║" , "╔" , "╗" , "╚" , "╝" , "╠" , "╣" , "╦" , "╩" , "╬"  } ,
    { "─" , "│" , "╭" , "╮" , "╰" , "╯" , "├" , "┤" , "┬" , "┴" , "┼"  } ,
};

const std::wstring rena::builtin::bc_w_table[4][11] = {
    { L"─" , L"│" , L"┌" , L"┐" , L"└" , L"┘" , L"├" , L"┤" , L"┬" , L"┴" , L"┼"  } ,
    { L"━" , L"┃" , L"┏" , L"┓" , L"┗" , L"┛" , L"┣" , L"┫" , L"┳" , L"┻" , L"╋"  } ,
    { L"═" , L"║" , L"╔" , L"╗" , L"╚" , L"╝" , L"╠" , L"╣" , L"╦" , L"╩" , L"╬"  } ,
    { L"─" , L"│" , L"╭" , L"╮" , L"╰" , L"╯" , L"├" , L"┤" , L"┬" , L"┴" , L"┼"  } ,
};
