/**
 * This file is auto-generated by `src/tools/update_box_chars.py`
 * 
 * DO NOT EDIT!!!
 * 
 * If something is wrong, please fix it in `src/tools/templates/update_box_chars/box_chars.cpp.in` first
 */

#include"box_chars.h"

const std::string rena::builtin::bc_sll_h = "─";
const std::wstring rena::builtin::bc_sll_h_w = L"─";
const std::string rena::builtin::bc_sll_v = "│";
const std::wstring rena::builtin::bc_sll_v_w = L"│";
const std::string rena::builtin::bc_sll_dr = "┌";
const std::wstring rena::builtin::bc_sll_dr_w = L"┌";
const std::string rena::builtin::bc_sll_dl = "┐";
const std::wstring rena::builtin::bc_sll_dl_w = L"┐";
const std::string rena::builtin::bc_sll_ur = "└";
const std::wstring rena::builtin::bc_sll_ur_w = L"└";
const std::string rena::builtin::bc_sll_ul = "┘";
const std::wstring rena::builtin::bc_sll_ul_w = L"┘";
const std::string rena::builtin::bc_sll_vr = "├";
const std::wstring rena::builtin::bc_sll_vr_w = L"├";
const std::string rena::builtin::bc_sll_vl = "┤";
const std::wstring rena::builtin::bc_sll_vl_w = L"┤";
const std::string rena::builtin::bc_sll_dh = "┬";
const std::wstring rena::builtin::bc_sll_dh_w = L"┬";
const std::string rena::builtin::bc_sll_uh = "┴";
const std::wstring rena::builtin::bc_sll_uh_w = L"┴";
const std::string rena::builtin::bc_sll_vh = "┼";
const std::wstring rena::builtin::bc_sll_vh_w = L"┼";
const std::string rena::builtin::bc_slh_h = "━";
const std::wstring rena::builtin::bc_slh_h_w = L"━";
const std::string rena::builtin::bc_slh_v = "┃";
const std::wstring rena::builtin::bc_slh_v_w = L"┃";
const std::string rena::builtin::bc_slh_dr = "┏";
const std::wstring rena::builtin::bc_slh_dr_w = L"┏";
const std::string rena::builtin::bc_slh_dl = "┓";
const std::wstring rena::builtin::bc_slh_dl_w = L"┓";
const std::string rena::builtin::bc_slh_ur = "┗";
const std::wstring rena::builtin::bc_slh_ur_w = L"┗";
const std::string rena::builtin::bc_slh_ul = "┛";
const std::wstring rena::builtin::bc_slh_ul_w = L"┛";
const std::string rena::builtin::bc_slh_vr = "┣";
const std::wstring rena::builtin::bc_slh_vr_w = L"┣";
const std::string rena::builtin::bc_slh_vl = "┫";
const std::wstring rena::builtin::bc_slh_vl_w = L"┫";
const std::string rena::builtin::bc_slh_dh = "┳";
const std::wstring rena::builtin::bc_slh_dh_w = L"┳";
const std::string rena::builtin::bc_slh_uh = "┻";
const std::wstring rena::builtin::bc_slh_uh_w = L"┻";
const std::string rena::builtin::bc_slh_vh = "╋";
const std::wstring rena::builtin::bc_slh_vh_w = L"╋";
const std::string rena::builtin::bc_dll_h = "═";
const std::wstring rena::builtin::bc_dll_h_w = L"═";
const std::string rena::builtin::bc_dll_v = "║";
const std::wstring rena::builtin::bc_dll_v_w = L"║";
const std::string rena::builtin::bc_dll_dr = "╔";
const std::wstring rena::builtin::bc_dll_dr_w = L"╔";
const std::string rena::builtin::bc_dll_dl = "╗";
const std::wstring rena::builtin::bc_dll_dl_w = L"╗";
const std::string rena::builtin::bc_dll_ur = "╚";
const std::wstring rena::builtin::bc_dll_ur_w = L"╚";
const std::string rena::builtin::bc_dll_ul = "╝";
const std::wstring rena::builtin::bc_dll_ul_w = L"╝";
const std::string rena::builtin::bc_dll_vr = "╠";
const std::wstring rena::builtin::bc_dll_vr_w = L"╠";
const std::string rena::builtin::bc_dll_vl = "╣";
const std::wstring rena::builtin::bc_dll_vl_w = L"╣";
const std::string rena::builtin::bc_dll_dh = "╦";
const std::wstring rena::builtin::bc_dll_dh_w = L"╦";
const std::string rena::builtin::bc_dll_uh = "╩";
const std::wstring rena::builtin::bc_dll_uh_w = L"╩";
const std::string rena::builtin::bc_dll_vh = "╬";
const std::wstring rena::builtin::bc_dll_vh_w = L"╬";
const std::string rena::builtin::bc_rll_h = "─";
const std::wstring rena::builtin::bc_rll_h_w = L"─";
const std::string rena::builtin::bc_rll_v = "│";
const std::wstring rena::builtin::bc_rll_v_w = L"│";
const std::string rena::builtin::bc_rll_dr = "╭";
const std::wstring rena::builtin::bc_rll_dr_w = L"╭";
const std::string rena::builtin::bc_rll_dl = "╮";
const std::wstring rena::builtin::bc_rll_dl_w = L"╮";
const std::string rena::builtin::bc_rll_ur = "╰";
const std::wstring rena::builtin::bc_rll_ur_w = L"╰";
const std::string rena::builtin::bc_rll_ul = "╯";
const std::wstring rena::builtin::bc_rll_ul_w = L"╯";
const std::string rena::builtin::bc_rll_vr = "├";
const std::wstring rena::builtin::bc_rll_vr_w = L"├";
const std::string rena::builtin::bc_rll_vl = "┤";
const std::wstring rena::builtin::bc_rll_vl_w = L"┤";
const std::string rena::builtin::bc_rll_dh = "┬";
const std::wstring rena::builtin::bc_rll_dh_w = L"┬";
const std::string rena::builtin::bc_rll_uh = "┴";
const std::wstring rena::builtin::bc_rll_uh_w = L"┴";
const std::string rena::builtin::bc_rll_vh = "┼";
const std::wstring rena::builtin::bc_rll_vh_w = L"┼";
