name: Sync External Files

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Sync ~/cmake/icu4c_dep.cmake
        run: wget -O icu4c_dep.cmake https://raw.githubusercontent.com/renalibs/cmake_utils/refs/heads/main/icu4c_dep.cmake
        working-directory: ${{github.workspace}}/cmake

      - name: Extract Branch Name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Push Files
        uses: actions-js/push@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          author_email: ${{secrets.BOT_EMAIL}}
          author_name: ${{secrets.BOT_USERNAME}}
          message: sync external files
          branch: ${{steps.extract_branch.outputs.branch}}